### ISSUE TITLE
[Needed] - Improve appearance of main menu

### ISSUE THREAD

**Issue by Colima-97** [Colima-97/MySQLvsMongo#22]
It looks awful

![image](https://user-images.githubusercontent.com/22593949/68758013-9936d500-05d2-11ea-8fa8-d830fea490a6.png)

I'd love to see the options well separated.

Also, I think we need to change the quote "Inserte una opción" for "Inserte un número".

**Comment by carlosfigueroa97** [comment]
@Colima-97 I think that would be 'Elija un número'.

**Comment by Colima-97** [comment]
> @Colima-97 I think that would be 'Elija un número'.

Sounds better!
