### ISSUE TITLE
[P1][Task5] - Except and Else statements tratament

### ISSUE THREAD

**Issue by Colima-97** [Colima-97/MySQLvsMongo#8]
This is about **r_data(db, table)** method and the structure:

```
try:

except SystemError:
    pass
else:
    pass
```

As I'm analyzing the problem, I realize that "else" statement is not required; this is it because the data is already beign sent in the `if - elif - else` statement, so a final `else` in the `try - except` structure is unnecessary.

So, the final code should look similar to:

```
try:
    #The code we already have
except:
    print('>>Error al crear los datos')
    print(sys.exc_info()[0])
```
This is my idea, but I'd love to hear your point of view @carlosfigueroa97 .

**sys.exc_info()**
> This function returns a tuple of three values that give information about the exception that is currently being handled. [...] Otherwise, the values returned are (type, value, traceback).

**sys.exc_info()[0]**
> Their meaning is: type gets the exception type of the exception being handled (a class object);

[Python sys documentation](https://docs.python.org/2/library/sys.html)

**Comment by carlosfigueroa97** [comment]
I agree with you bro!

**Comment by carlosfigueroa97** [comment]
Very good bro. I congratulate you for your work.
