### ISSUE TITLE
[P2] - [TASK-3] - [FIX] - Two or three corrections

### ISSUE THREAD

**Issue by Colima-97** [Colima-97/MySQLvsMongo#9]
I noticed two important issues and both are related with those three methods:

![image](https://user-images.githubusercontent.com/22593949/68729118-ba75d200-058e-11ea-842e-90ef1e08ea63.png)

1.  We got to rename the method __r_data(db, table)__ because the "__r__" could be easily confused with "__read__", since above are two methods called like that.

2. When we are working with files (reference below), we need to have `try - except` statements

![image](https://user-images.githubusercontent.com/22593949/68729433-9ff02880-058f-11ea-86dd-90ff34626ae7.png)

3. This is not that important, but is a good practice to use one language with your variables

![image](https://user-images.githubusercontent.com/22593949/68729615-12610880-0590-11ea-91da-2ecf65b81d9f.png)

I know that we are using at the same time english and spanish, but we are using them in two very well differentiated contexts (English for _python_, Spanish within _MySQL_)

**Comment by Colima-97** [comment]
Don't seek the methods by the index, because I've increased the code, so indexes won't match.
Just seek them by the name

**Comment by carlosfigueroa97** [comment]
> 
> 
> Don't seek the methods by the index, because I've increased the code, so indexes won't match.
> Just seek them by the name

How by index? I don't understand

**Comment by carlosfigueroa97** [comment]
@Colima-97 What do you name propose for the methods?.
What do you think "read_data_files"?

**Comment by Colima-97** [comment]
> @Colima-97 What do you name propose for the methods?.

What name(s) do you propose for the methods?

> What do you think "read_data_files"?

What do you think about rename it as "read_data_files"?

**Comment by Colima-97** [comment]
> > Don't seek the methods by the index, because I've increased the code, so indexes won't match.
> > Just seek them by the name
> 
> How by index? I don't understand

Yeah, the numbers in the left side of the image

**Comment by Colima-97** [comment]
Bro, I didn't accept your PR #12 because I already fixed the `try- except` statements in my #15 PR. 

Also, a lot changed there, I recommend you to check out the changes (#15).

Anyway, I appreciate your work.

**Comment by Colima-97** [comment]
Done! #20 PR
